### ISSUE TITLE
Convert to RoR (jk)

### ISSUE THREAD

**Issue by lsamayoa** [mcka1n/transaction-stats#1]
Now you've come to the darkside :)

**Comment by mcka1n** [comment]
@lsamayoa I just noticed your _Issue_ I will be happy to convert it to RoR but I'm forcing myself to refresh my Java skills haha

Spring ... I kinda like it now! 

![image](https://user-images.githubusercontent.com/1958982/37053551-bb671446-217c-11e8-9a0d-bf1ccf8d22b9.png)
